apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:z4DLabbX7zZ6hVR54MDvXhRUYbk=,iv:1T7D+IIdKenpoarpcE1lzS+BLqhZya9KS0dUAMHtML4=,tag:nUZbtl9l8NQQJa2NQW6GLQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Gdh0Ig==,iv:KpPbRyzpeFZZwBgq6OWN9oj7UNIwp7cE9w641m/S0cw=,tag:MUf4FSKg2BnsQlBIVbl6Xg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:WASVle6RfHsTMEoV43m5mDt0jSj2sBXVcnsP3JDTSyWz8fFzjbbq0ksiPTQbMibB4Jij27RLNL7zYFiBydmBV5MkV+rjriyZExXKaJE53zyTLTjKVH21GQ==,iv:4LwAvurSDKqxSJ/A4TvgtLwkhJVUH0mIEu25FZ9ki9Q=,tag:l7qzdsJGaBwzF31kctxN3Q==,type:str]
    DB_PORT: ENC[AES256_GCM,data:tLw+7dU1NEg=,iv:EztidXeBAbtNmF1HhjjCVhjkNGHzvQ8HatZLs65HwRs=,tag:r8YIMH98MWko1fw6VemlYA==,type:str]
    DB_URI: ENC[AES256_GCM,data:LsAyyO0WhJB3hWBuLWYGJW0d8cEj1KUspfk5e3frWSsaQyjTY5oXDCrusyLpDHVMBbpV2B0UDCBINxqTjWneJEnEZrHM8s80oPvXotYOMmn5eUqE9OLQ0Em+0VAzEqiwPEq27W+KCb19LJP/Jrj/f03im2ZsaQqQl1LQbUnkaAjkiTmff9qNAUCJclU0DMIRh6L2YOU/kYiIswZl,iv:j/la89W19ROXz5ncPY401KVg8Nnyg1SOqqQbz5qKg9g=,tag:AZFX6CEevdwNslT5S64Rkw==,type:str]
    DB_USER: ENC[AES256_GCM,data:bPIQzg==,iv:HD3+xfdTA0E4YVADsKSpXRyfS1BJHDnEVbxTTp2ZLoc=,tag:E1q4t0J+98VGpNsLzbxyfQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:T7seGg==,iv:RCxM+n+MWBgbqL5LVny8YmfQW+6FEMo3DINI7SBjCj0=,tag:f+b5OnXXItYJVJJprupjPQ==,type:str]
kind: Secret
metadata:
    name: external-db-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVW0yTmZuNG9kWlppbHlZ
            N3NoQjZ4aHQyczdqL094Mi9yT2lXUmtsUVRrCmlPc1J2OXJwR1JYcUhkYWc2OEJt
            QitkQmlTSERmR3ZsZ1JLV21iNnlnalUKLS0tIEdGQWRMTzRUMHhBMmpsRjUwVUhZ
            MDNoZlIxd2U1WWZqc3dUZElQcTRVUE0K83PVYYNGtif93FhNPGtvCrsgMxIqCU1a
            J0gBFVp2C0nMYav/+mmXRtnndIpzZcNcFRPOG50wJKOoAHSvHdwdaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T00:14:21Z"
    mac: ENC[AES256_GCM,data:BVS9Z6hlM/ToyDlBiWd+9T+Dksl5xDA7OrWHqa7bCVYu0k6R6EN368hMQ0oil6/QgRiZcNH7n9u5sBxv/wV1VhoSu/g5ApVoCVVqQtBTQl1e2ABtFPPPp4OWY+wR696SRL4sIUi9h0KVChBhS1TVbwTsTNeORNm61R6y5519epY=,iv:MNvNAx80h5Eur9vg85AZPQOHKRzPEXuQmzmUu5IzDXY=,tag:WYPVe0WXy1D5/wLzlO/wxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
