apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v3.1.2
          name: mealie
          ports:
          -  containerPort: 9000
      #     volumeMounts:
      #       - mountPath: /app/data
      #         name: mealie-data
      # volumes:
      #     - name: mealie-data
      #       persistentVolumeClaim:
      #         claimName: mealie-data
          env:
          - name: DB_ENGINE
            value: postgres
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_SERVER
            value: data-cluster-rw.databases
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: external-db-credentials
                key: DB_NAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-db-credentials
                key: DB_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: external-db-credentials
                key: DB_USER