apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-cluster
  namespace: databases
spec:
  instances: 3
  storage:
    size: 1Gi
    # pvcTemplate:
    #   accessModes:
    #     - ReadWriteOnce
    #   resources:
    #     requests:
    #       storage: 1Gi
    #   volumeMode: Filesystem
