apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:6eqtj9xlffD3pPE5QrWuPW0HCSM=,iv:kTNx5UHboITTpN/W8GZDLSD7pdq4ZrH9M49EE3JV2hY=,tag:PM0njyRPE0pfyH5FUf52XQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:y0tPBw==,iv:h/NWOtZe1rDTXiNe9MvCsyJ9pFQd43eMug0/TmXiCjQ=,tag:XaZF7zz0BRlnJ0mMD3r0Yg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:DmVyndAyhugUyibta86xBvC9OlS0HvGP/8UCKkWr+CDVR61qKumVqNVQqAuE13HVITKlroPmYCHrgiZepdoDTzojQgDwBTbG9Nm8Bkh78rg0xUXJph8UGA==,iv:hQV1bGZAcqI4KCDhgoNfbGwAVpO+2V9WV4VGcSuIm4E=,tag:NQA0tXReAKutf0517r/fQA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:CIiz6PG26xE=,iv:RsNcEGYBbOHbfhV00P/vL1OWup5Wsu65wbnMpWgbVto=,tag:JALL6A3/vbouagEmeFA3bQ==,type:str]
    DB_URI: ENC[AES256_GCM,data:4X/luloDi3NBhZyeVFsuPaaa8pbddwP+nSa9cATDdz2ws53sp8rz2jcetOsafaLCLbkIOl6sa5vcN5gf+wtuy2+0mPTLopZxCVK0r3Ggf95GTy+3bpcL1CR8PdiqSujLXyi/v8aPGjUm93P5tAhkem2hMBLyHxlAcLCa59u8C90qFVe8BGGBPcd60HMZq8OwPos2AwPMLu3/hiWt,iv:y5Wofrx0WaPv+d3pSG9FqzpPGmKCsQD8Dl3qGX/Z7Aw=,tag:VDy0VPCahkS4usz7WaU0VQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:E8So4w==,iv:C+PbSeQJnM7tVobtyJcr8fUSM462qI6abQ8jSwAXBus=,tag:yqdpcDobCsulSfu90JzLVA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:PmSI8Q==,iv:zmMoW795mEzwb+EmjzT8vIXde9EDKS4JKKwpc/8Of5g=,tag:XtvuW3OU9Ff+gL+1F1O0Nw==,type:str]
kind: Secret
metadata:
    name: external-db-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZUQ2ZitpTWl1MmxQQ2R0
            a2Z4amRaUVExU01ubG9YekRwby90bHJmeHdjCjdmT2lTMURSbnlrT0hwS1EyOHJS
            d1RHaVY2WUJ0THB2aTc4L3BtYzRuRkUKLS0tIFZwQXRpendGWXU0SGE2WEp4akxa
            RysxeHVzbDgxNDU5SHVUQnc2WUlQUFEKiixuoJtndE8RLG/xI+M87618FsfHxbx4
            1PeUNIQJhYogz1Tyesxjxfmb3B1cZmWL1xXJpBNMq2GPsW9Qe3pAdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T01:24:13Z"
    mac: ENC[AES256_GCM,data:CG50JVgEzH+myPPBBbnvSxSRpWfD4fHT1ktvA1FmLReXt124xvI8FXiPn5UDuhROpBlyAR2iBvcGxb+2/zQZzjprvVh7gsLIBZGPyC86QLLeIHgI/I073MEScQk82A5xCnXKj69n7EtQgitWeiUT+K18YefRPeHVUbHxhvOt1ss=,iv:7GuBS+XS8Glac9aWMC5kqimWsR2MvXbqQaL/iNzTUlE=,tag:BQAXm5qsf2+EPbySy5OGZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
