apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:p9EdY3r4GWA+d8JnR/vjvVbuukQ=,iv:HsoRgSQ6wigCAB5Zs/XuO++me5jG+8dvO+WRBg9dCEU=,tag:YnT7V/MJ+Zhj0HLFUvCA3w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:ZkirQA==,iv:hGzcn7IJndzfdmkas/JW56qxFPFi4RsAO7kxkQibWjk=,tag:cdE0JqgQD+Fn00CYsM1IXQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Fc/pHgenBWcOaq5Jifrhz9xETjk0QO5PN6q01BJzAAATQk2VeBvWW0KCuO3ByxhRQPVoFb3AlET/jWzgRaWvyOsJ57q+3RdYM/Bljs87owirBi/RGh4wGg==,iv:q8bEQg4h5BaWpgFyaSSErMsoJDy3VOSJDqvqeM4lc8M=,tag:kLYowwA5cSZyJ3PkRbVtNA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:TVGLOgW/qgM=,iv:7eL4vjXkr8YHxptdlgE8grUSst6ybLzdJ12UWJE1HEk=,tag:wIHkFojDxg5DFsljSq6fzQ==,type:str]
    DB_URI: ENC[AES256_GCM,data:z3a4z90hj1PfWe1aW+XBsM7/fh+CS6QqcnydV/T4UX3tjVxR8mQfVS/IDfO/kpI4v/jZ3FbIWC3G/1YFGGz1Ih9OSt29OGIdbNFT608rVbq4kRH5733zdy4NBmddtkvev8CRaWwLrYy5hBmEjgwPVAG9Ge5C1E81Y8ZJVEsNZhANC+yoY3nyeYePBBCmVJ6dNkvuGL41GyIyM7E5,iv:1lAGCGnlnkWJMcys+rwlAjKCNVsnb64NYS8kK3CwPoY=,tag:bBN8kf5PmRkd5AHQKjHuAA==,type:str]
    DB_USER: ENC[AES256_GCM,data:6Xjznw==,iv:aQ1nQQBHJ8YocXS/8xHYl0by5ep/1ML5U1FGKqWtlx8=,tag:xXWLudURJzeSJDoM8g7zGA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:tCpc1A==,iv:AFmi3HjDWDC9CCZ4mte0E/02Q0Etf+3PeRCcb6rzxUo=,tag:Ab0VRvRjuGGt3pFHmYm78w==,type:str]
kind: Secret
metadata:
    name: external-db-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcjNVK0VWc0FMK3V6MTBL
            aVNENDltVkxYbVIzL3E2K2dQMVJlQStlYzF3CkJubjhrUjdBWFlvLzlHMTA3UUFy
            V0x2TkU2RTg2cHIrQ2FtUGE3ZGgwQUEKLS0tIEoyejlNSGIzbVY4bE14anlSa2FI
            enRsYzNSS3RPQmhFdXFpVFZtRGV5aEUKfP9B9UqJfUpS+BQazwABL/TMqcvfQOG3
            NwPc5XefyzHM3GmJprKAxG//3bFi/g6sN8HClSpyAuypD39H+YUsxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T21:30:44Z"
    mac: ENC[AES256_GCM,data:Y+OoXVQ47enKCmU3pllFBiCPxV43LSgrBFdlOIPEqtAlIlG5t32uq53vaVcG+6jIsQOfcZd2WZWc2+3tMHOBA8lULACqctMXG8EWiknkYIAf/ZPMd9tH8YcYrVSebBSx78A+MFQYoDtrJL06VaguBboE8I3uj4zalxJmIXddy9g=,iv:jNiYVJhUqp4sfXb+obguEX6Rb7Ic6mi9L1xMx9KNeRU=,tag:vo+hqKkcHcoA16UxV1ZJGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
