apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:k0Cw5w1eYe5vpftP,iv:BUaVX6GseNWQfzBRKDWVuk66MshuFpBrQueVqABETRE=,tag:lJFRjfy/kgG5JDmrEDrkpw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:7soKtA==,iv:lgivbjap5yiNP3n0m39O/D7GxRknNaOQy3ZYsO/K/jo=,tag:q6nygkb1Sg3wpTx9B57S7w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Rt8A7kkZZgOi8TIephCheyh+VYU+s+HNGVu/DXUD5Gce6e8xrb+OXHjgMh2YiQQpmt1SjJrCj7i1OHeNC0h/WBh2G4zYRc4nI7FwIcflehN+aqpCfS+Qjg==,iv:m0GNyMCSj9e65nGhsBx4TBzWW0ZpkTOoGjQTGzSQof0=,tag:78m0+he3QYnh1Spm0FPnNA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:hnXMpj2Zs4c=,iv:FBwIWfRL/ELQRgXJQni7CexjBGhnSxnZUynMYF/v4Aw=,tag:m4jAIa0lvy4dzosIgttpZA==,type:str]
    DB_URI: ENC[AES256_GCM,data:7T7FQB5SZpmQOYOdyc/kAanE68tdcVp11vzx0H+cK9UNJfrawYKSsbOe4IkshI8ofMIXhKV8DYIAaGljraTiJ6zUS18UDxfvLrhw6LuvWgKXDq8kzLPaqgglOXCUeLoshzKfe0oZf134l4UdsQ/QfLDa0GI5BMg/isxjgB8kMyIhCSeON/VNkj+eRwUWKNgkeJWivehCRvGSF/eW,iv:t686KOFA4gLAqOjmB8hMeqG2LZGxqXJt4/3jGhRKIHU=,tag:tBx7DGD3vrHHwBw/w+GGvg==,type:str]
    DB_USER: ENC[AES256_GCM,data:fGr7qQ==,iv:X/0MZFmU9KUogTebBS4t7QAdrx7yiPcG3+PjI3wtSmo=,tag:PyiJel7CC6t+ObATL0VsOA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Tu8kOA==,iv:wPTS4we67cKOzKeT7JXPnTVXKnye1DxFh6Y0gg/Nj9c=,tag:ShAcEWSxj/0KEfsHTWK/dw==,type:str]
kind: Secret
metadata:
    name: external-db-poc-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSWxCRnlHL2RtVTlrVHd6
            S1dLZmtmLzY2b1ByVkQ0VTlQR2hpZEZZU1I0Ci9CR09xZTFCSkNHM244TURPMGZV
            bG96bC9mZUZJaWc0cm41S3krZUpBU2cKLS0tIHpRRzY1ajVGWkt0MUk3TDdURi8z
            VkxSMVR5eDNVajhMK2h1V1ZUaU1VMWsK3EToSEaM0tGyn8X49zqXHj3/ABCB6PKi
            FohGrbos4VqsJcRVgwek2K+1gGeOk6uWiqs8LsO+QzuDxjtftsjUnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T07:06:59Z"
    mac: ENC[AES256_GCM,data:r+3qBc/ltUzQMOf/iaqAeDKCbNI+uHbsOlUiOMQxq18Eif3lHyRMETbCpiGQu34+5Mk8MxmOoY1ep+xPCZ01k86o5lH8Coxz0IC52LHcYOPCk9xsBjgs4FxKHxjp9Qe2RRAoF+LgdxMR4A25WMow/FNNwKd3LMWpA6Jn6WsVry0=,iv:JrgdhtLhsghf1YV70+bmkvGx2a5A/0ryWSeldMN6ebU=,tag:bJw5svm6p/k4JsvCMfyBzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
