apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:QuiiOaEu06NJrjIs9W6KLiXh+6OnWCtk2q1sw5O1gncZD+M9+NUp4gOBCzVarvORgnAy9/t8aRE=,iv:QeTjYqqccCvZbscwbfgaydUwZtSRwou9NI1E+UUDb6A=,tag:tYIYXSyWgvypp7KbBxYt/A==,type:str]
    DB_NAME: ENC[AES256_GCM,data:RbxsoQ==,iv:/W6ouJWRGZ4LczuXchzeZlp39JkgfldkkHWjfy14IrI=,tag:WgrPnaKWHaAQy1qPYJIqOw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:38atTGfo3kAo+Lk5OiESzqlbvVdOgKfyYHQoIPBqjt+trOmpcghObImjRd5zZ70kvMQQsFo28mqaAFdxOhKowlzBEnXWdWwaykFjkUTCv6e521pJZR33TA==,iv:LopUp9eON3lQ1oRYQYUWEMBOpye7Y/xyrhk2xn09l5Q=,tag:aaZobt6VCrmCJmzUd/mbOg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:2qy1myd1wTU=,iv:mfrFvLtoAg85xu5G25tmsrocge8Tz0Shj/D4xUawobw=,tag:e1Ye/n0bcxx9iKjyt664dA==,type:str]
    DB_URI: ENC[AES256_GCM,data:efK+kTHk/jtcABEMAcEgvje8dbtoan0WOAGjuYuOOnygrQsxLPYkNGdqOVutqCjCoJRkXdLAlW8My4HtaBoXaNLP+Fof84NdvGcHcezQsBRKms3ezgCnxoW6+q+bxmWtpeqbqhaEpDrG9zCcGHE5FB7tqsai2RUQP2q3s1cswCJjnejRHvKZAQnAv2OQQc51oEHOXOZy8SMqbWZS,iv:/uMTCoY+nMalDwHMZ3ZL6meng2mPNL0Hj7qsgs1KpP4=,tag:fpymanKogwJhRlxm2GkIqg==,type:str]
    DB_USER: ENC[AES256_GCM,data:WLcidg==,iv:hOOP2Nk9hrAKP6q6sYANO2oB4ngqbfcaX4ULAo1isFA=,tag:PgYYZC5Hq5YDXlLaaAyhoQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:hN+5rA==,iv:aGij7be4KbUK6eD5lUTkDWwG9H2pikPUoRAISD9medk=,tag:R6L2J16NDyyc88+iCmeSTA==,type:str]
kind: Secret
metadata:
    name: external-db-poc-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHlMWGZKR1oySXhEU3Nv
            c1pnNjNydzVsR1B5SlZDQW9nSys4TnZtcWowCjcwcm1WbnRDZW9naXJmYXJOSUNK
            U0c2c3MyV1BFRmRpRmxpanBUWWp6ZVUKLS0tIEFoMUNVNjBvdEhXeFg3VnVFbnB1
            dk9JLzYrdGNiSVRzVVNFQlpXZy9FcDQKVWjTy7oGeOwtC65SJSaqzmYSk59g+1or
            98rd6Rc0SNw6SdoMO7xtoaqMmOhIgP4PioCKSo5DKB2kkIFuBffR5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T01:25:15Z"
    mac: ENC[AES256_GCM,data:FyvI9nv0V/mOo+pozOkprO8SgC6Ww/w0qqTD64buhVvrZu7S+iQqrQT72sZUXRA0JwhJzlrF50eG5oIVfyxHe29JhYO4yLrNWNcLZZGA10M6j2DUcepOdiTG1uVotnYQAiUesSJRovX9AQq0u3829bxQK8exENEO8VHv1XX/1Do=,iv:xmF0Cy/RZRHiaQt3BtQEl2/r2C9GyKdnwAxvQxBSWas=,tag:IZlsO2kqwvTExK9GBl4aTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
