apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:si8bXYmXEJDkvzOkdnvIRDQ3Cs8=,iv:QrMX3FxwGgnfr1CNrFBc/vP31ePcN8HVtIWAIwVMjms=,tag:oWnv/YkBQiTIEPzjtzKGBQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:scZK5A==,iv:i7TIA+YUpvFPBSU9kaKWDpbSR44SWSv2UpofbCi1sWo=,tag:S5tNhy0+xFuISPKbJ3sx+w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ns8hAq4H9iIksgeviJgKCLoqndcV5BiXzWirnVIAKEv/OLffqZhFDfKmrXaThdirVIIAKcoxnAOMJMd2eBZ4xvCYwZlpqP9CvkU69ThB2LdVHYxvFUcKbA==,iv:7Jr+RvKj3NfOqGfDRrzRM9HmaKZUT6t9jB5fzaWVme8=,tag:y6dhXHCZbLZX5ImEmNkohw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:alp/uIR9D/M=,iv:aJxSrcOgYQo2l/xViNEDq5iDvFNoueMqiPQs804ajRM=,tag:PS0+ForNL57X2NvnM7hP1Q==,type:str]
    DB_URI: ENC[AES256_GCM,data:tpNWjfoqM2J0bpA7SUY8zbzodzd2HYua5VAEh+43qps8gofxj4OuPCfVP/hTuRV9GTDVuQ3EMuMDilhQMBt8t8QVapy2UA4oOEzwU6yJfaXw2zoKtWhSSD7eQrnS2EBAIj7hlcr4Adz/VteijH83aoEHWVdiWBZ3NrdEG8pnT7SF5/nrNc8kLzBoy0jOZK45qQ9wq3H1ZjJm0pr+,iv:SMf9V6PRYuVRe6mypxcN5+371b8CHVtHyAixAhyTXZQ=,tag:PWR0LVJmOsyjmQ25CJYdCQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:wmNEQw==,iv:Vhf8JHzOdKx6J9H7SNdxLKkbPqNfvYILVxFMa+t8MbY=,tag:8cNZR4nBNqNmnQWYsbHK8Q==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ZIr0QQ==,iv:ngxOpkUr5dJjhP0ozulXB+kfOo/+vofFMQ+CCmcuCMo=,tag:Mm8Wm3JmSkl25QGV/ZhZwg==,type:str]
kind: Secret
metadata:
    name: external-db-poc-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdURKbG5ING5nUDkxR0xZ
            Q21PeXh0aHhWSVIySUZERTZZMGk0NzFFajJNCko5Q05oTXZmdkY2bFdnU0tXMVJH
            VkZ4dC9JamFVakNaQ1JhTGMwNUtqd2sKLS0tIFF1RGZrQkt0T1I3MDRGSk94ZnRk
            MmpPT05uMVAvaGlSUmhjTWhFSUI5ZWMKF+kwuNEtpsofzZQ9x0Bp0cucc8x0kRJH
            0dsL/8vim+cgkda2YCMig0jBg09Fes5tSHSkpUEpsIHBhEJqCJLfCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T02:34:09Z"
    mac: ENC[AES256_GCM,data:+y2q4ZkH54TTdvQ2ZrpOWR+LcwcYMwgVwcC5QH/CSxca7/8kgoOR8uml+7k6Qz66n5OTT9VUw569dHU4NFlR7ppxwyMzUuC6JQ3gb4dhfx28GI0aJTOpJQFeSzOHbRepKVGf8nhWIDRIO0BndM4BCTBsU5XnT79S2R0MiO9QJGk=,iv:5CsRN5nNEfRSRG2690F884A01pN7+d2z0a2JclwjeNQ=,tag:owEkHZWTUY+8xdbXEYmrtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
