apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:CKfQsJsgrVYu/+Zzp58sqFWrzNU=,iv:IMyxYKppDAccRxE/xLoTACJmBGZRHCFdsZq6EzxdIOg=,tag:aBI1OzHB6a2exT4riEElhA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:2Dbdew==,iv:8KLcn4Qchabz3XxlFZKAnrKgSCvDqgAPIK+U8DRO+bw=,tag:Ec7lGypmfAgxGpXMmU4/ZQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:hYj9FchQy0oGwgeVHTK2SFe7WDa7kRftI72qdZ4F5S8/fd5TWGl9dLR38j3pOuEW8DEVGDo0ybLWhRMMfj3Iz8yoLwdN33yZLwK95/WzjCHdt7OZt/M6hg==,iv:KeZk4H+LNam5zAr/F0QPWTnKVZdmkJ6hS6B3XH42wPs=,tag:VfY3Ec/SHYRbSscNxUNXdA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:6q0ughWM0p0=,iv:wBdrilQsMM40WYZHEtUG54DeJvhoFvFUlQ8Ta0XHLNw=,tag:A4MVUASN6GmogDLsVroOnA==,type:str]
    DB_URI: ENC[AES256_GCM,data:rTtixQqGb7fNQxEsgFNEmQ/1+a3DmWsqPJIEWe1/hqgIq78evd9rOrc7UA9dS05VURIEu9L+99mwciYrHpASxpebMZjeZiB0B5Nkj+r6ty/yXVGBIFc7RhThPVyPfVhhap6TbYZHWS6Kr95NP8buCt0jGBFiGlsvWtIG6d4Pe+EoQhZ2QEdnlgnHuaONo6laY0eFJI0TN4R7gSnu,iv:9wU8AMGEkqvQoEb6zI6Kpf1dLPqY8qwoc4MsjjcvsK4=,tag:GVqVi8rSxxgSUl/yYHKTOQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:QcIzeA==,iv:7NRmjI64WaI9T5iUreU7BZmWCyrYtENWf3nh8MhfVnY=,tag:U1GK0Q2k03ZvAifVdh91LQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:LfYxqw==,iv:hewA0nvl705k4+3yRjwvHAmipIzQ1jn8NWo/EZ+9OaM=,tag:Cnk0ACvSZqGoAv6Arnonhg==,type:str]
kind: Secret
metadata:
    name: external-db-test-credentials
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbEZwd2JNbktKZDBYblpR
            ZzZlVTl4YXZRSFF1bFVWWHZhQWZTZERiUkZJCmhzMzhsTzR0Qzl4S1IrTmFDMzRs
            R3ZIK3dMWFJkN1JBaGR5RGs5ZzBGN1kKLS0tIDlrTmF3MzdoVE9yWWZRSS9HeUVT
            SlJsemVkSjVmWDcrNTFyV0FDYlRvSmsKyGz5o2RPOLv0gkWTVJ6XewpN/XFSBXF/
            szHytUHmw/7RkkZEWBgiZvQajphVc+vP6JKBnEIw9GNUrRdcbyaM1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T00:33:57Z"
    mac: ENC[AES256_GCM,data:JOBP/YeGL9RyLmfKTsxdGIDoh17a4w5LMydcodFE8D2zdCnYuzSGlC0idHHPMpFqUHHPoxx5QGcUAUnwqQ13bCfzIbB4Wq6h8L801ibRmbgL6upYrGivicQNvtkHxkqB+vjVT/m4IfDzZb6WgFF8YtXKg49fogDmh+7sSpFjRxc=,iv:cmkPZSw390bT7IesedlRAUCF6oPckD/yOI3SpBnX7cM=,tag:9gpYPsj7jIVN2mCJpK6Svg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
