apiVersion: apps/v1
kind: Deployment
metadata:
 name: linkding-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding-test
  template:
    metadata:
      labels:
        app: linkding-test
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.43.0
          ports:
            - containerPort: 9090
          env:
          - name: LD_SUPERUSER_NAME
            valueFrom:
              secretKeyRef:
                name: super-user-creds
                key: LD_SUPERUSER_NAME
          - name: LD_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: super-user-creds
                key: LD_SUPERUSER_PASSWORD
          - name: LD_DB_ENGINE
            valueFrom:
              configMapKeyRef:
                name: linkding-configmap
                key: LD_DB_ENGINE
          - name: LD_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: linkding-configmap
                key: LD_DB_PORT
          - name: LD_DB_HOST
            valueFrom:
              secretKeyRef:
                name: external-db-poc-credentials
                key: DB_HOST
          - name: LD_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: external-db-poc-credentials
                key: DB_NAME
          - name: LD_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-db-poc-credentials
                key: DB_PASSWORD
          - name: LD_DB_USER
            valueFrom:
              secretKeyRef:
                name: external-db-poc-credentials
                key: DB_USER

          volumeMounts:
            - name: linkding-data-poc
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data-poc
          persistentVolumeClaim:
            claimName: linkding-poc-pvc
